version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii-app
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/html/.env
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: yii-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii
      MYSQL_USER: yii
      MYSQL_PASSWORD: yii
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
